name: Post RSS to Bluesky

on:
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Post to Bluesky
        uses: joschi/blueskyfeedbot@v1
        with:
          rss-feed: "https://briscape.com/feed.xml"
          username: ${{ secrets.BLUESKY_IDENTIFIER }}
          password: ${{ secrets.BLUESKY_PASSWORD }}
