name: Post RSS to Bluesky

on:
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Post to Bluesky
        uses: joschi/blueskyfeedbot@v1
        with:
          feed: "https://briscape.com/feed.xml"
          bluesky-identifier: ${{ secrets.BLUESKY_IDENTIFIER }}
          bluesky-password: ${{ secrets.BLUESKY_PASSWORD }}
